In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve().parent
SRC_PATH = PROJECT_ROOT / "src"

if str(SRC_PATH) not in sys.path:
    sys.path.append(str(SRC_PATH))

print("PROJECT_ROOT:", PROJECT_ROOT)
print("SRC_PATH:", SRC_PATH)

PROJECT_ROOT: /Users/amirhosseinlatifinavid/Desktop/Programming/Python /quant-ml-backtester
SRC_PATH: /Users/amirhosseinlatifinavid/Desktop/Programming/Python /quant-ml-backtester/src

In [2]:
from quant_ml.config import TICKERS, START_DATE, END_DATE, FRED_SERIES
from quant_ml.data_loader import (
    download_yahoo_data,
    save_yahoo_data,
    download_fred_series,
    save_fred_data,
)

In [3]:
prices = download_yahoo_data(
    tickers=TICKERS,
    start_date=START_DATE,
    end_date=END_DATE,
)

prices.tail()

Price           Close                                                  \
Ticker            EEM         GLD         IWM         QQQ         SPY
Date
2025-12-23  54.310001  413.640015  251.632385  621.326538  686.086304
2025-12-24  54.419998  411.929993  252.261276  623.144287  688.499695
2025-12-26  54.799999  416.739990  250.973557  623.104309  688.429871
2025-12-29  54.660000  398.600006  249.436295  620.088135  685.976562
2025-12-30  54.880001  398.890015  247.589569  618.649902  685.138916

Price                       High                                      ...  \
Ticker            TLT        EEM         GLD         IWM         QQQ  ...
Date                                                                  ...
2025-12-23  86.877693  54.330002  413.760010  252.770360  621.626148  ...
2025-12-24  87.403923  54.459999  412.630005  252.411004  623.493883  ...
2025-12-26  87.115990  54.820000  418.450012  252.301197  624.732261  ...
2025-12-29  87.443642  54.680000  403.760010  251.053413  621.995764  ...
2025-12-30  87.235138  54.990002  403.799988  249.705800  621.396439  ...

Price             Open                                       Volume            \
Ticker             IWM         QQQ         SPY        TLT       EEM       GLD
Date
2025-12-23  251.971778  617.421489  682.057268  86.450751  25319700  13193300
2025-12-24  251.522585  621.206728  686.076320  87.135847   9565300   6718400
2025-12-26  252.131500  623.873298  688.758989  87.473430  11352000  10476200
2025-12-29  249.815609  619.319085  685.667409  87.324492  18816700  20679200
2025-12-30  249.526127  619.059420  685.577720  87.115989  24643000  10179000

Price
Ticker           IWM       QQQ       SPY       TLT
Date
2025-12-23  24973500  41120400  64840000  33624100
2025-12-24  12103000  18468700  39445600  25942000
2025-12-26  17429900  28959800  41613300  26522700
2025-12-29  25218800  32458300  62559500  29399800
2025-12-30  22123600  31226800  47160700  25106800

[5 rows x 30 columns]

In [4]:
print(prices.shape)
print(prices.columns[:10])

(3519, 30)
MultiIndex([('Close', 'EEM'),
            ('Close', 'GLD'),
            ('Close', 'IWM'),
            ('Close', 'QQQ'),
            ('Close', 'SPY'),
            ('Close', 'TLT'),
            ( 'High', 'EEM'),
            ( 'High', 'GLD'),
            ( 'High', 'IWM'),
            ( 'High', 'QQQ')],
           names=['Price', 'Ticker'])

In [5]:
price_path = save_yahoo_data(prices)
price_path

PosixPath('/Users/amirhosseinlatifinavid/Desktop/Programming/Python /quant-ml-backtester/data/raw/yahoo_prices.parquet')

In [6]:
import os
import sys

print("Python executable:", sys.executable)
print("Conda env key exists:", bool(os.getenv("FRED_API_KEY")))
print("Env name check done.")

Python executable: /opt/homebrew/Caskroom/miniconda/base/envs/data/bin/python
Conda env key exists: True
Env name check done.

In [7]:
fred_api_key = os.getenv("FRED_API_KEY")
print("FRED key loaded:", bool(fred_api_key))

FRED key loaded: True

In [8]:
macro = download_fred_series(
    series_map=FRED_SERIES,
    api_key=fred_api_key,
)

macro.head()

            fed_funds    cpi  unemployment  10y_treasury  2y_treasury
date
1947-01-01        NaN  21.48           NaN           NaN          NaN
1947-02-01        NaN  21.62           NaN           NaN          NaN
1947-03-01        NaN  22.00           NaN           NaN          NaN
1947-04-01        NaN  22.00           NaN           NaN          NaN
1947-05-01        NaN  21.95           NaN           NaN          NaN

In [9]:
macro_path = save_fred_data(macro)
macro_path

PosixPath('/Users/amirhosseinlatifinavid/Desktop/Programming/Python /quant-ml-backtester/data/raw/fred_macro.parquet')